"""query_panels engine_runs

Revision ID: 163cd3cc9b7f
Revises: 3a697237e7f0
Create Date: 2026-07-16 20:18:53.604490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '163cd3cc9b7f'
down_revision: Union[str, None] = '3a697237e7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('queries_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_panels_shop_id'), 'query_panels', ['shop_id'], unique=False)
    op.create_index('uq_query_panels_shop_fingerprint', 'query_panels', ['shop_id', 'fingerprint'], unique=True)
    op.create_table('engine_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cited_sources_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cited_brands_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('our_mentions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['query_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_runs_panel_id'), 'engine_runs', ['panel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engine_runs_panel_id'), table_name='engine_runs')
    op.drop_table('engine_runs')
    op.drop_index('uq_query_panels_shop_fingerprint', table_name='query_panels')
    op.drop_index(op.f('ix_query_panels_shop_id'), table_name='query_panels')
    op.drop_table('query_panels')
    # ### end Alembic commands ###
