"""verifications table — Phase 4 share-of-model delta (public schema)

Grain is (run_id, engine), NOT PRD §8's fix_id — see app/models/verification.py for why that
grain is superseded. Per-fix survives as the measured_fixes_json manifest (GIN-indexed).

FK asymmetry is deliberate: run_id (the post scan) CASCADEs like share_of_model.run_id, while
baseline_run_id / panel_id SET NULL like engine_runs.run_id — every pre-side value is
denormalized onto the row, so the measurement record survives deletion of old run metadata.

Revision ID: 2bf30ca663a2
Revises: 530075ef94b8
Create Date: 2026-07-28 18:54:00.098544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bf30ca663a2'
down_revision: Union[str, None] = '530075ef94b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('baseline_run_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('panel_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('pre_rate', sa.Float(), nullable=True),
    sa.Column('post_rate', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('pre_mentions', sa.Integer(), nullable=True),
    sa.Column('post_mentions', sa.Integer(), nullable=True),
    sa.Column('pre_total_queries', sa.Integer(), nullable=True),
    sa.Column('post_total_queries', sa.Integer(), nullable=True),
    sa.Column('competitor_deltas_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('measured_fixes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('measured_fix_count', sa.Integer(), nullable=False),
    sa.Column('published_at_max', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settle_hours', sa.Float(), nullable=False),
    sa.Column('settle_satisfied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['panel_id'], ['query_panels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'engine', name='uq_verifications_run_engine')
    )
    op.create_index(op.f('ix_verifications_baseline_run_id'), 'verifications', ['baseline_run_id'], unique=False)
    op.create_index('ix_verifications_measured_fixes', 'verifications', ['measured_fixes_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_verifications_run_id'), 'verifications', ['run_id'], unique=False)
    op.create_index(op.f('ix_verifications_shop_id'), 'verifications', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_shop_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_run_id'), table_name='verifications')
    op.drop_index('ix_verifications_measured_fixes', table_name='verifications', postgresql_using='gin')
    op.drop_index(op.f('ix_verifications_baseline_run_id'), table_name='verifications')
    op.drop_table('verifications')
    # ### end Alembic commands ###
