"""agent_runs_run_id

Revision ID: 4d303431605b
Revises: f3f760e6f250
Create Date: 2026-07-17 22:42:44.017072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d303431605b'
down_revision: Union[str, None] = 'f3f760e6f250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['query_panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_panel_id'), 'agent_runs', ['panel_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_shop_id'), 'agent_runs', ['shop_id'], unique=False)
    op.add_column('engine_runs', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_engine_runs_run_id'), 'engine_runs', ['run_id'], unique=False)
    op.create_foreign_key(
        'fk_engine_runs_run_id_agent_runs', 'engine_runs', 'agent_runs',
        ['run_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_engine_runs_run_id_agent_runs', 'engine_runs', type_='foreignkey')
    op.drop_index(op.f('ix_engine_runs_run_id'), table_name='engine_runs')
    op.drop_column('engine_runs', 'run_id')
    op.drop_index(op.f('ix_agent_runs_shop_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_panel_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
