"""fixes publish audit columns

The Publisher's (step 4) audit trail. Both nullable, both NULL on every non-published row, one
meaning each — see ``app/models/fix.py``:

* ``publish_error`` — why a publish failed (which write, what Shopify returned). Shown to the
  merchant on a ``publish_failed`` row so a failure reads as a cause, not a dead end.
* ``published_at`` — set ONLY on a confirmed post-write re-read, never on the mutation's HTTP 200.
  It means "verified live on the store", and it is the timestamp Phase 4's Verifier and any
  staged-rollout audit read.

``fixes.reason`` keeps purely grounding/to-do semantics and is untouched. No new status column:
``fixes.status`` is a plain ``String(16)``, so ``publish_failed`` is a code-only addition.

Revision ID: 530075ef94b8
Revises: c1f2a3b4d5e6
Create Date: 2026-07-28 09:54:56.894130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530075ef94b8'
down_revision: Union[str, None] = 'c1f2a3b4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixes', sa.Column('publish_error', sa.Text(), nullable=True))
    op.add_column('fixes', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixes', 'published_at')
    op.drop_column('fixes', 'publish_error')
    # ### end Alembic commands ###
