"""share_of_model

Revision ID: f3f760e6f250
Revises: 163cd3cc9b7f
Create Date: 2026-07-17 21:58:57.692208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3f760e6f250'
down_revision: Union[str, None] = '163cd3cc9b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_of_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('our_rate', sa.Float(), nullable=True),
    sa.Column('our_mentions', sa.Integer(), nullable=True),
    sa.Column('total_queries', sa.Integer(), nullable=True),
    sa.Column('competitor_rates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'engine', 'period', name='uq_share_of_model_shop_engine_period')
    )
    op.create_index(op.f('ix_share_of_model_shop_id'), 'share_of_model', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_of_model_shop_id'), table_name='share_of_model')
    op.drop_table('share_of_model')
    # ### end Alembic commands ###
