/**
 * `customers/data_request` — one of Shopify's three mandatory compliance webhooks.
 *
 * ACKNOWLEDGE-ONLY, and that is the accurate answer rather than a shortcut.
 *
 * Quixly analyses a merchant's catalog and how visible it is to AI shopping engines. It never
 * receives, requests, or derives an end customer's personal data. Every table on both sides was
 * enumerated when this was written: agent-side `public` holds shops, products, ingest_runs,
 * query_panels, engine_runs, agent_runs, share_of_model, audits, fixes and verifications — catalog
 * and measurement data keyed by shop. The query panels are generated by `graph/interrogator`, so
 * even the engine queries are synthetic; no real shopper is involved. App-side, Prisma owns only
 * `Session`, whose name/email columns identify the *merchant's staff*, not the merchant's
 * customers. There is therefore no record anywhere that a data-subject request could match.
 *
 * So this returns 200 with an empty result set, because the result set genuinely is empty.
 * Forwarding to the agent to "look" would be theatre against tables that structurally cannot
 * match, and would put a customer identifier into a service that has never held one.
 *
 * IF QUIXLY EVER INGESTS CUSTOMER-LINKED DATA — orders, reviews, customer segments — this stops
 * being a no-op and must return the stored data to the merchant within 30 days.
 *
 * Verification is the library's: `authenticate.webhook()` checks the HMAC against the raw body
 * under SHOPIFY_API_SECRET and throws 401 on an invalid signature (400 on a missing header)
 * before anything below runs.
 */

import type { ActionFunctionArgs } from "react-router";

import { authenticateWebhookSerialized } from "../lib/webhook-auth.server";

export const action = async ({ request }: ActionFunctionArgs) => {
  // Serialized like every other webhook route: this topic arrives while the app is still
  // installed, so a session exists and the library would refresh a near-expiry token OUTSIDE
  // the per-shop rotation lock. See lib/webhook-auth.server.ts.
  const { shop, topic } = await authenticateWebhookSerialized(request);

  // Shop and topic only. The payload carries the customer's id, email and phone — logging it
  // would create the very customer record this handler exists to say we do not keep.
  console.log(`Received ${topic} for ${shop}; no customer data is stored, nothing to return.`);

  return new Response();
};
